name: Publish Portfolio to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Install Dependencies and Build Static Website
      working-directory: website
      run: |
        yarn install
        yarn build
      
    - name: Publish to GitHub Pages
      working-directory: website/build/tech-portfolio
      run: |
        cd website/build/tech-portfolio
        touch .nojekyll
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} INPUT_DIRECTORY=$(pwd) publish.sh
