# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Publish Portfolio to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: joatmon08/tech-portfolio
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Install Dependencies and Build Static Website
      working-directory: website
      run: |
        yarn install
        yarn build
      
    - name: Publish to GitHub Pages
      working-directory: website/build/tech-portfolio
      run: |
        touch .nojekyll
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} INPUT_DIRECTORY=$(pwd) publish.sh

