name: Publish Portfolio to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Install Dependencies and Build Static Website
      working-directory: website
      run: |
        yarn install
        yarn build
      
    - name: Publish to GitHub Pages
      working-directory: .
      run: |
        touch .nojekyll
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} INPUT_DIRECTORY=$(pwd) publish.sh

# Upload the build output as a Pages artifact
    - name: Upload Production Artifacts
      uses: actions/upload-pages-artifact@v1
      with:
        # Point this to your final build output directory
        path: website/build

  # Deploy job
  deploy:
    # Make sure it waits for the build to finish
    needs: build
    runs-on: ubuntu-latest
    # Required permissions for GitHub Pages deployment
    permissions:
      pages: write
      id-token: write
    
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
